# Generated by Django 5.2.7 on 2025-10-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_create_weektopic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weektopic",
            options={
                "verbose_name": "נושא שבועי",
                "verbose_name_plural": "נושאים שבועיים",
            },
        ),
        migrations.RenameIndex(
            model_name="weektopic",
            new_name="api_weektop_topic_9c6f4e_idx",
            old_name="api_weektopic_topic_idx",
        ),
    ]
