# Generated by Django 5.2.7 on 2025-10-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_weektopic_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="קישור")),
                (
                    "type",
                    models.CharField(
                        choices=[("פורמלית", "פורמלית"), ("מתפרצת", "מתפרצת")],
                        max_length=20,
                        verbose_name="סוג",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("קלה", "קלה"),
                            ("בינונית", "בינונית"),
                            ("קשה", "קשה"),
                        ],
                        max_length=10,
                        verbose_name="רמת קושי",
                    ),
                ),
                (
                    "additional_role_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_role_tag_simulations",
                        to="api.roletag",
                        verbose_name="תגיות תפקיד נוספות",
                    ),
                ),
                (
                    "additional_sim_topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_topic_simulations",
                        to="api.simulationtopic",
                        verbose_name="נושאים נוספים",
                    ),
                ),
                (
                    "additional_weeks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_week_simulations",
                        to="api.weektopic",
                        verbose_name="שבועות אפשריים נוספים",
                    ),
                ),
                (
                    "main_role_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_role_tag_simulations",
                        to="api.roletag",
                        verbose_name="תגית תפקיד מרכזית",
                    ),
                ),
                (
                    "main_sim_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_topic_simulations",
                        to="api.simulationtopic",
                        verbose_name="נושא מרכזי",
                    ),
                ),
                (
                    "main_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_week_simulations",
                        to="api.weektopic",
                        verbose_name="שבוע מרכזי",
                    ),
                ),
            ],
            options={
                "verbose_name": "סימולציה",
                "verbose_name_plural": "סימולציות",
                "indexes": [
                    models.Index(fields=["type"], name="api_simulat_type_9e01d1_idx"),
                    models.Index(
                        fields=["difficulty"], name="api_simulat_difficu_210cda_idx"
                    ),
                ],
            },
        ),
    ]
