# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations


def clear_all_data(apps, schema_editor):
    """Clear all existing data before model changes."""
    Simulation = apps.get_model('api', 'Simulation')
    Simulation.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """Reverse operation - do nothing."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_color_serial_to_topic_type'),
    ]

    operations = [
        migrations.RunPython(clear_all_data, reverse_clear_data),
    ]
