# Generated by Django 5.1.3 on 2025-10-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clear_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simulationtopictype',
            name='api_simtype_serial_idx',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='additional_role_tags',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='additional_sim_topics',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='additional_weeks',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='main_role_tag',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='main_sim_topic',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='main_week',
        ),
        migrations.AddField(
            model_name='simulation',
            name='author',
            field=models.CharField(default='מחבר לא ידוע', max_length=100, verbose_name='מחבר'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='api.roletag', verbose_name='תפקיד'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_topics',
            field=models.ManyToManyField(blank=True, related_name='simulations', to='api.simulationtopic', verbose_name='נושאי סימולציה'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='week_topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='api.weektopic', verbose_name='נושא שבועי'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['author'], name='api_simulat_author_ec67d7_idx'),
        ),
    ]
